### ISSUE TITLE
Domain modelling

### ISSUE THREAD

**Issue by pklepa** [notstoe/flaggy-rn#7]
## Description
We need to draft a general Domain modelling for the game design.

Ideally, the outcome of this story is to have a high level definition of all the game's entities and data flow drafted as a decision chart.

### Data Reference
JSON object containing all the supported countries with:
  - Country Code
  - Country Name
  - Flag image source
  - Continent
  - Related Country Codes (preset)

## Game State
- Game Mode - Enum of:
  - Flag Count
  - ~~Timer~~
- Progress
- Past Flags (to avoid repetition)
- Current Flag
- Current Options (?)

**Comment by pklepa** [comment]
@notstoe @gvituri, please take a look at [the FigJam drawings](https://www.figma.com/board/BTKRDL65ELMiONjGoGbSQj/Flaggy?node-id=0-1&node-type=canvas&t=YTZiFqLKtSWJAuG7-0) containing the current definitions for:
- Project Entities
- Application Flowchart
- Business logic processes

For brevity, here's a couple of stills from the current domain modelling:
![Image](https://github.com/user-attachments/assets/de54807a-f627-4105-a39a-272dc8ca801f)

![Image](https://github.com/user-attachments/assets/5097b788-1543-409b-92dd-cde0990437e6)

![Image](https://github.com/user-attachments/assets/609e3bc9-7635-4793-8eeb-c4f2bb4d6967)

**Comment by notstoe** [comment]
Seems good, I think everything we need is there. 

We should add a highscore local var that will be updated on game over? So when the app is closed, at least that will persist for now. 

We'll probably use this library for that: [mmkv](https://github.com/mrousavy/react-native-mmkv)

And for handling game state locally, we can use zustand? [zustand](https://github.com/pmndrs/zustand)

**Comment by gvituri** [comment]
Looks good to me!

Here are the changes I've included:

- Added Capital to Country Entity
> Added it with the '?' since it is not something we currently need, but something that could possibly come later as it's own game mode (gets a flag/country name, has to pick it's capital);
![Image](https://github.com/user-attachments/assets/a84ef1ec-83e6-4864-bce2-d2bcf99a6996)

- Expanded App FlowChart to include post Game Over Options
> Nothing major, just a "play again" button leading to the game restarting and a "menu" button leading the player to the landing page
![Image](https://github.com/user-attachments/assets/6de304cf-6ff8-424d-8b4e-29454c1788c9)

- Expanded App FlowChart to include Profile tab flow
> Simple in/out page with a single process of locally stored data retrieval and display and option to return to landing page
![Image](https://github.com/user-attachments/assets/4b0f892d-0e7e-415a-8f43-9aedd97163f8)

**Comment by pklepa** [comment]
Awesome, great additions. Think we're good to go. I'll close this issue and we can amend these definitions as we go if needed
